; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27045.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\QinDong.DESKTOP-VHM6NLV\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
